apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-config
  namespace: titanic
  labels:
    app: titanic-api
data:
  FLASK_APP: "run.py"
  FLASK_ENV: "production"
  DB_HOST: "titanic-db-service"
  DB_PORT: "5432"
  DB_NAME: "titanic_db"
  APP_SETTINGS: "production"
