apiVersion: v1
kind: Secret
metadata:
  name: titanic-secrets
  namespace: titanic
  labels:
    app: titanic-api
type: Opaque
stringData:
  DB_USER: "titanic_user"
  DB_PASSWORD: "titanic_password_prod_change_this"
  SECRET_KEY: "production-secret-key-change-this-to-random-string"
  DATABASE_URL: "postgresql://titanic_user:titanic_password_prod_change_this@titanic-db-service:5432/titanic_db"
